### ISSUE TITLE
Does not compile properly using PyInstaller

### ISSUE THREAD

**Issue by urdans** [Embarcadero/DelphiVCL4Python#12]
I made VCL for Python as shown on webinar "Introduction to Python GUI Development with Delphi for Python - Part 1: Delphi VCL for Python".
When I run thes code it works fine. VCL form is shown correctly.

But when I created a single exe-file using pyinstaller (pyinstaller -F -w --onefile testdelphivcl.py) and ran created exe-file I got the error:

![error](https://user-images.githubusercontent.com/15079497/152278981-1ed4f286-0e5b-4fb0-a5af-0ba81ca58daf.png)

**Comment by Priyatham10** [comment]
Thank you for the posting the issue @urdans. Working on it. Will comment as it resolves.

**Comment by Priyatham10** [comment]
I understand your concern. You want to make the GUI application available as a .exe file to others using `pyinstaller` and distribute it. I resolved your issue by going through all `pyinstaller` documentation but we expect a small work before making the executable file work.

**Comment by Priyatham10** [comment]
When you create .exe file using `pyinsataller -w --onefile testdelphivcl.py` command, `--onefile` argument embed the information of creating necessary binaries on the fly in the temporary folder like it created `C:\\Users\\wizar\\AppData\\Local\\Temp\\_ME1108402` from the above image in your case.  The `-F` and `--onefile` arguments are the same. You can handle this error by removing the `--onefile` argument and running the command 
`pyinsataller -w  testdelphivcl.py` 

- This creates a folder - **testdelphivcl** in the **dist** folder instead of direct single _testdelphivcl.exe_ file. 

- You can find the *testdelphivcl.exe* file inside the **testdelphivcl** folder. In that **testdelphivcl** folder.

- I want you to create a folder named **delphivcl**. 

- Confirm the folder structure until now: **...>dist>testdelphivcl>delphivcl**

- Now, create an empty file named _moduledefs.json_ json file in the **delphivcl** folder: **...>dist>testdelphivcl>delphivcl>moduledefs.json** 

- Now, create a folder named **Win64** or **Win32** based on your computer configuration inside the **delphivcl** folder. Confirm the folder structure: **...>dist>testdelphivcl>delphivcl>Win64**

- As you installed the `delphivcl` your computer stores a file named `DelphiVCL.pyd`. Search for `DelphiVCL.pyd` in your File Explorer --> copy the `DelphiVCL.pyd` file and paste it inside **Win64** folder. The folder structure here is: **...>dist>testdelphivcl>delphivcl>Win64>DelphiVCL.pyd**

- Now, just double-click the exe file: **...>dist>testdelphivcl>testdelphivcl.exe** to see your GUI app result.

**Comment by urdans** [comment]
Thank you very much for your help.
I did all the steps but I am getting this message: "Failed to execute script activity".
My app is called activity. Any idea what is happening?

**Comment by Priyatham10** [comment]
Are you saying that your file app name is `activity.py` but not `testdelphivcl.py`? I took the reference of your error issue posted in which you only posted the command `pyinstaller -F -w --onefile testdelphivcl.py` which says your app name is `testdelphivcl.py`. I just edited my answer. I recognized that we don't even need to create the `moduledefs.json` empty file by ourselves which gets created by itself.

And please post the image of where you're getting the error "Failed to execute script activity". Because it runs smoothly to me as I tested. I need to see your screen to understand what's happening.

**Comment by lmbelo** [comment]
@Priyatham10 @urdans I'm collection some information and working on a test project. I'll bring the result as I work on it.

**Comment by maxkleiner** [comment]
When I run the exe generated by py2exe or pyintstaller, vcl window doesn't shows up.
Maybe input() prevent the window from closing until  press enter?

**Comment by Priyatham10** [comment]
@maxkleiner Did you follow the steps i mentioned to:

- Run without using `--onefile` argument 
- Creating the **delphivcl** folder inside file folder which is inside the **dist** folder
- Creating **Win64** folder inside **delphivcl** folder
- Copying and pasting the **DelphiVCL.pyd** file in **Win64** folder
- Running the exe file
- then running the exe file inside file folder

You should get the VCL window pop up as you implement these steps..

**Comment by maxkleiner** [comment]
It comes from the winapi: C:\maXbox\works2021\maxbox4\examples\dist\dist>pyinstaller --debug --log-level=D
EBUG 2> mxerr.txt --onefile hellodelphivcl.py
import '_winapi' # <class '_frozen_importlib.BuiltinImporter'>
Fatal Python error: initfsencoding: unable to load the file system codec
LookupError: unknown encoding: utf-8

**Comment by lmbelo** [comment]
@maxkleiner is the Python interpreter shared library available?

**Comment by maxkleiner** [comment]
Which lib do you mean?

**Comment by lmbelo** [comment]
I got it working here:

1) Create a folder named "MyApp";
2) Place your script file into the folder;
3) Run the PyInstaller script: pyinstaller -w [YOURSCRIPTFILE].py;
4) Download the delphivcl module and the shared libraries from the GitHib repository: 
   - https://github.com/Embarcadero/DelphiVCL4Python/tree/main/delphivcl;
   - https://github.com/Embarcadero/DelphiVCL4Python/tree/main/lib.
5) Navigate through the generated folders:
   - MyApp->dist->[YOURSCRIPTFOLDER]
   - Place the downloaded delphivcl module into the current folder (MyApp->dist->[YOURSCRIPTFOLDER]);
     1) Open the **\_\_init\_\_.py** file and change the following code:
         ```
        #Setup moduledefs.json
                 if moduledefs.get_auto_load_defs():
                     moduledefs.try_load_defs(False)
        ```
        **to:**

        ```
        #Setup moduledefs.json
                 if moduledefs.get_auto_load_defs():
                     moduledefs.try_load_defs(True)
        ```
     2) Or simply make sure you're not distributing the **moduledefs.json** file.
   - Place the download Win32/Win64 folders into the delphivcl folder (MyApp->dist->[YOURSCRIPTFOLDER]/delphivcl).
6) Run the generated .exe file (MyApp->dist->[YOURSCRIPTFOLDER]/[YOURSCRIPTFILE].exe);
7) Follow the attached sample for further details.

![image](https://user-images.githubusercontent.com/8376898/152820672-e1d2895c-1c30-47a8-9847-7748cc25de3a.png)
![image](https://user-images.githubusercontent.com/8376898/152816381-5dc18e50-cb76-4f44-a28f-f0d992de057d.png)
![image](https://user-images.githubusercontent.com/8376898/152816438-2f723ec9-38bc-438e-a10f-35ab722b821e.png)
![image](https://user-images.githubusercontent.com/8376898/152820880-459e212c-d3f9-408b-b185-2dd016872955.png)
![image](https://user-images.githubusercontent.com/8376898/152816551-19f06b10-067b-48c0-ab27-8500e0182b70.png)
![image](https://user-images.githubusercontent.com/8376898/152821266-c1f279fe-7014-4194-a3f6-d2ecb4295f82.png)
![image](https://user-images.githubusercontent.com/8376898/152816689-7fd6fd33-878b-4257-a4cd-b9cc8ca58933.png)

**Comment by lmbelo** [comment]
[MyApp.zip](https://github.com/Embarcadero/DelphiVCL4Python/files/8016632/MyApp.zip)

**Comment by lmbelo** [comment]
> Thank you very much for your help. I did all the steps but I am getting this message: "Failed to execute script activity". My app is called activity. Any idea what is happening?

It is failing because you're sharing an existent **moduledefs.json**.

**Comment by lmbelo** [comment]
> Which lib do you mean?

The Python .dll. 
Take notes from the moduledefs.json and moduledefs.log, they may contain some helpful traces.

**Comment by maxkleiner** [comment]
Got a standalone at least, point to improve are the lines:
 `sdir = os.path.join(os.path.dirname(os.path.abspath(__file__)), libdir) ` //__init__.py
and `return os.path.join(os.path.dirname(os.path.abspath(__file__)),  "moduledefs.json") ` //moduledefs.py
with __file__ implicit changed to '__file__' and the mentioned /Win32 it runs as a standalone exe with the lib subdirectory

However, it seems the sys.path is blank when its called from an EXE generated by pyInstaller. This same behaviour occurs when you run the python interactive command line and try to fetch sys.path[0].

Using sys._MEIPASS does not work for one-file executables. From the docs: For a one-folder bundle, this is the path to that folder, wherever the user may have put it. For a one-file bundle, this is the path to the _MEIxxxxxx temporary folder created by the bootloader . Use sys.executable for one-file executables. –
https://stackoverflow.com/questions/61207991/error-when-calling-a-python-function-from-c


![1096_standalonepyvclexe](https://user-images.githubusercontent.com/3393121/152872960-595ad82e-31ec-465c-a3cc-3be89c9e1f5c.png)

**Comment by urdans** [comment]
It works now for me. I did what @Priyatham10 indicated. Thank you!

**Comment by Priyatham10** [comment]
Great! Keep posting any further issues. Thank you and we'll consider your improvement suggestions @maxkleiner
