### ISSUE TITLE
Problem with virtualenv: "Could not open python 310.dll"

### ISSUE THREAD

**Issue by danieleteti** [Embarcadero/DelphiVCL4Python#4]
This project is simply **awesome**! Good job guys.

I'm having a problem while using virtualenvs

![image](https://user-images.githubusercontent.com/1428644/149375802-a9c1174f-6c59-4046-828d-280861af6543.png)

I did the same test using python 3.9 and the problem is the same. 
The problem doesn' happens using the system Python installation (without venvs).

Thanks

**Comment by lmbelo** [comment]
Hi, @danieleteti! 
Thanks for the report.
Python4Delphi requires Python to be compile with the "--enable-shared" symbol, once it consumes the Python interpreter .dll.
I'd suggest you to try again using miniconda on conda itself.

**Comment by pyscripter** [comment]
@lmbelo 
P4D supports venvs (see .  
The issue is that when P4D is used to develop extension modules such as delphivcl, the standard search for the python dll should not be applied (looking in the registry etc.).  The python dll is already loaded in the execution space and you want to work with the very same dll.  It should be enough to call LoadLibrary('pythonxy.dll') without specifying a directory.   Also a lot of the stuff that initializes python etc. I think they are not needed.   We probably need a different version of LoadDLL for use in extension modules.

**Comment by lmbelo** [comment]
@pyscripter have a look at the following link:

https://github.com/Embarcadero/python4delphi/blob/master/Modules/DelphiFMX/ModuleSpecs.pas

We are doing something similar on Linux. It is still not supported on delphivcl and delphifmx (non-Linux).

**Comment by pyscripter** [comment]
@lmbelo 

I don't think any of that stuff is needed at least not in Windows and quite likely not in Linux either.  I don't know about Android.
See my latest commit.  I have added a new method LoadDLLInExtensionModule.  It skips all stuff related to python initialization, since python is already initialized.  It also bypasses the registry on Windows and GetDLLPath returns ''.

If you look at the [documentation of LoadLibrary](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryexa) it says that if the DLL is already loaded (which is this case its) then it is used and you do not need the path.

As a proof of concept I have modified the DemoModule project to use the LoadDLLInExtensionModule.  It works well with all python versions and venvs as well.

**Comment by lmbelo** [comment]
Ok, cool. I will have a look. Thank you.

**Comment by pyscripter** [comment]
Another approach would be to use [EnumProcessModules](https://docs.microsoft.com/en-us/windows/win32/psapi/enumerating-all-modules-for-a-process) to find out which python dll is loaded and load that file.

In linux one could use [dl_iterate_phdr](https://linux.die.net/man/3/dl_iterate_phdr)

**Comment by lmbelo** [comment]
The example I sent you before is a sort of Python library on Linux that doesn't provide a shared library, the symbols are on the host executable.

**Comment by pyscripter** [comment]
I am not sure what you mean.  I though you are trying to use delphivcl with standard python distributions.  In windows and linux pyhon.exe is using a shared library pythonxy.dll or libpythonxy.so or something.

**Comment by lmbelo** [comment]
Have you tried delphifmx with miniconda on Linux? It doesn't load a shared library.
Run the delphifmx and enumerate the loaded libraries, there is no shared library loaded, but it export the API symbols in the host executable.

**Comment by pyscripter** [comment]
> Have you tried delphifmx with miniconda on Linux?  
No I haven't.

**Comment by lmbelo** [comment]
Regarding the host exported symbols, same may occur on macOS.
The current way we are setting up the Python environment works well, and doesn't affect the original P4D library, which was indeed our main concern.
Venv is still not supported by the delphivcl because I haven't introduced the same changes we made in the delphifmx here in the delphivcl.

**Comment by pyscripter** [comment]
Anyway, LoadDLLInExtensionModule makes sense in all systems.   Python is already initialized.  There is no need to initialize it again.   And you need to make sure you are using the same DLL as python.exe.

**Comment by lmbelo** [comment]
Cool. Thanks!

**Comment by pyscripter** [comment]
> Python4Delphi requires Python to be compile with the "--enable-shared" symbol, once it consumes the Python interpreter .dll.
> I'd suggest you to try again using miniconda or conda itself.

I see what you meant.  This is an issue on Linux and not on Windows that the original report was referring to.   From what I see the standard python3 on Ubuntu and other distributions is statically linking libpython.  But I tried miniconda and this also statically links libpython.  Does this mean the delphifmx cannot run on linux standard distributions?

**Comment by lmbelo** [comment]
@danieleteti we have introduced venv support. Can you try again, please?

**Comment by Priyatham10** [comment]
We now successfully got it working with all;

* System-level Python
* System-level Python virtualenv
* VIrtualenv installed under conda
* Conda environments

Please see the supporting screenshots:

**Sytem level Python virtualenv**:

![image](https://user-images.githubusercontent.com/17174106/155247239-775c571d-5d24-4e9c-92b0-a9aa8eecf278.png)

**Python virtualenv created inside conda**:

![image](https://user-images.githubusercontent.com/17174106/155247795-df995408-fdbf-46b6-a952-cae787a37af8.png)

**Comment by danieleteti** [comment]
> @danieleteti we have introduced venv support. Can you try again, please?

Hi, t seems to work.
I did the following

```
C:\CORSI\PythonWithDelphiUI
(venv) λ ls
samples/  venv/

C:\CORSI\PythonWithDelphiUI
(venv) λ pip install -U delphivcl
Requirement already satisfied: delphivcl in c:\corsi\pythonwithdelphiui\venv\lib\site-packages (0.1.29)
Collecting delphivcl
  Downloading delphivcl-0.1.37-cp310-cp310-win_amd64.whl (6.4 MB)
     |████████████████████████████████| 6.4 MB 6.8 MB/s
Installing collected packages: delphivcl
  Attempting uninstall: delphivcl
    Found existing installation: delphivcl 0.1.29
    Uninstalling delphivcl-0.1.29:
      Successfully uninstalled delphivcl-0.1.29
Successfully installed delphivcl-0.1.37
WARNING: You are using pip version 21.2.3; however, version 22.0.3 is available.
You should consider upgrading via the 'C:\CORSI\PythonWithDelphiUI\venv\Scripts\python.exe -m pip install --upgrade pip' command.

C:\CORSI\PythonWithDelphiUI
(venv) λ ls
samples/  venv/

C:\CORSI\PythonWithDelphiUI
(venv) λ cd samples\

C:\CORSI\PythonWithDelphiUI\samples
(venv) λ ls
helloworldvcl.py

C:\CORSI\PythonWithDelphiUI\samples
(venv) λ python helloworldvcl.py
```

And the simple form correctly shows up.

Thank you guys. From my POV this issue can be closed. ASAP I'll do more extensive tests.
